### ISSUE TITLE
Editor field bugs and delays

### ISSUE THREAD

**Issue by diggidong** [pwndoc-ng/pwndoc-ng#110]
I encounter a few problems with the editor fields in the vulnerabilities section.
I added two custom editor fields to my vulnerabilities.
The first issue is, when creating a new vulnerability, those editor fields are not editable. Also the cursor does not change from arrow to that "text insert marker" when hovering over that editor text field. It takes some time (like a minute) until the editor field becomes responsive and editable - it shouldn't be an issue by computing power.

The second issue is, once I created some vulnerability templates, the custom fields shows the data of previous opened vulnerability templates.
Like 'editor_textfield_1' in 'vuln_1' contains the text "sample text". After finishing editing that field I open 'vuln_2' and the 'editor_textfield_1' shows the data of 'vuln_1'. It also takes some time, until it gets refreshed with the appropriate data.

It seems to be a similar issue as mentioned in https://github.com/pwndoc-ng/pwndoc-ng/pull/84 .

Any ideas on that one?

**Comment by diggidong** [comment]
pwndoc is running local in a docker on an AMD Ryzen 5 5600X 6-Core Processor, the storage is also a nvme ssd.
I also don't see any peaks (cpu/ram) while running pwndoc at any time, so doesn't seem to be a hardware issue like I said.
It's running on localhost, so shouldn't go through network/router at all.

there is literally no big data at the moment. right now i am working with like 5 vuln templates, and 2 report templates just to get the report layout right before import more vuln templates and stuff.

maybe we can have a screenshare session, to figure things out.

**Comment by Serizao** [comment]
I just tried to reproduce the problem without success. Maybe you could make a video with the DevTools open where we see the network and the console, like this 

![image](https://user-images.githubusercontent.com/11671895/227588765-c29b8598-e4bc-48ae-bb3e-037717e6d6ed.png)

**Comment by diggidong** [comment]
I am on the master branch.

I think the problem is because of some connection problems with the websockets?

screencast: https://streamable.com/0aj0fk

**Comment by Serizao** [comment]
This PR should be solve uneditable editor for custom field

**Comment by Zeecka** [comment]
I can't reproduce. I just merged the PR, can you confirm the first issue is solved @diggidong ?

**Comment by Serizao** [comment]
On my side I was able to reproduce and the pr seems to solve the problem: the problem was due to the fact that it is impossible to make collaboration on a vulnerability (even if it is a Template) which does not exist yet

**Comment by diggidong** [comment]
> I can't reproduce. I just merged the PR, can you confirm the first issue is solved @diggidong ?

Works on my side too!

Thanks a lot for the great support guys!
