### ISSUE TITLE
cross-category sorting

### ISSUE THREAD

**Issue by diggidong** [pwndoc-ng/pwndoc-ng#111]
Hi everyone,

I am trying to sort the vulnerabilities only by the CVSS Score (cross-category).

For example:
I have two categories for vulnerabilities, 'General' and 'Web Application'.
Sometimes I need both categories in a report, as some vulns can be applied to both, web apps and network.
My problem is, if I have for example two vulns of 'Web Application' (high and medium) and one of 'General' (medium), but the medium vuln of the last one is higher rated regarding the CVSS Score as the medium vuln of the 'Web Application', it won't be sorted right in the final report.
In PwnDoc:
![image](https://user-images.githubusercontent.com/9928172/227524205-b722937d-1111-4ce3-8ffa-bec86053f155.png)

Thats how it looks like in the report:
![image](https://user-images.githubusercontent.com/9928172/227524490-3de89914-222b-4012-a6dc-8426b77e5478.png)

It seems like PwnDoc sorts the vulns based on the audit type and afterward by the CVSS Score.
Is there a way to sort all the vulns only by the CVSS Score?

**Comment by Zeecka** [comment]
Can you show me the template code you're using according to your report screenshot ?
I think you are using the default findings order with `{#findings}` loop which iterate over categories then CVSS (by default). You can modify your template with the loop `{#findings | sortArrayByField: 'cvssScore':-1}` that will reorder findings by CVSS first as expected.

**Comment by diggidong** [comment]
Amasing!
You were right, works like a charme.
Thanks again!
