### ISSUE TITLE
Custom Fields - Select Options broken when changing the language

### ISSUE THREAD

**Issue by diggidong** [pwndoc-ng/pwndoc-ng#132]
Hi,

I observed an issue regarding the select fields which I have created in the custom fields.
For example I have created a few select boxes (I know, radio's would fit better because only one choice is valid):
![image](https://user-images.githubusercontent.com/9928172/228343662-891980d9-3edc-4cce-99ec-f03e04570bbc.png)

In the default 'English' language they are select boxes, but when switching to another language, they become empty fields.
![image](https://user-images.githubusercontent.com/9928172/228343728-c9327bcb-f81d-4e3c-927c-f7b3515212dd.png)

Another issue is, once I have started a non english report, the custom fields select boxes are empty (which i kind of expect because the prior problem):
![image](https://user-images.githubusercontent.com/9928172/228344041-508b1ae0-fcf0-4116-a9fe-4d63f02b993d.png)

But once I change in the same report to the english language (which does have fine working custom field tempaltes), they behave strange:
![image](https://user-images.githubusercontent.com/9928172/228344293-e9822714-8589-48ed-80d6-b6437e92ce7a.png)

Now, I only can choose all of them (per section) at once - like clicking one, all others will also be un-/selected at the same time.
I only clicked 'Internet' once:
![image](https://user-images.githubusercontent.com/9928172/228344564-a3c36d2c-1f3f-4d42-8d70-6c548b98303d.png)
Same happens when I unselect one of them, the other one also gets unselected.

PS: where is the difference between 'select' and 'multiple select', because I am also able to check multiple fields with both?

**Comment by diggidong** [comment]
Oh, I think the select boxes are empty when changing the language, to be able to have different translations for different languages. That nice and behave as expected.
Once I defined those checks also in the second language, everything behaves as expected.

But an editor field in the same custom category overwrites the data in the different languages.
Looks like some inconsistency in the behavior here.

**Comment by Zeecka** [comment]
### Issue 1:

You have to provide options for each language, then the field will act as checkbox normally.

![image](https://user-images.githubusercontent.com/24873615/228799724-a76bc91c-f640-4099-905f-2790deaf615d.png)

### Issue 2:

I can't reproduce, I think it's related to issue 1. It works well when you define custom field in both languages (it even keep the selected option while switching language as long as you keep the same name).

**Comment by diggidong** [comment]
Should I open a separate issue for the last one?

**Comment by Zeecka** [comment]
I could reproduce what you were saying, I've just opened an new issue : https://github.com/pwndoc-ng/pwndoc-ng/issues/188 . Note: even if the editor display the wrong data in the field creation process, the value is well saved and you can achieve what you expect.
