### ISSUE TITLE
Unable to Login Anymore

### ISSUE THREAD

**Issue by bricekh2** [pwndoc-ng/pwndoc-ng#134]
This has happened to me a couple times now. Previously, I just rebuilt the entire thing because I didn't have Pwndoc really populated yet. My VM crashed and now I cant get back to a login screen. So far I have tried:

Restarting Docker
docker-compose down
docker-compose up
docker-compose up -d --build

When I go to 127.0.0.1:8443 it just never connects. For a brief moment it said token error in the address bar but only saw it once.

Since I am a noob I am sure I am missing something silly. I did back up the DB but I would like to figure out what the hell I am doing wrong to not be able to login again.

I have found this pwndoc-backend error:
 servers: Map(1) {
pwndoc-backend     |       'mongo-pwndoc:27017' => ServerDescription {
pwndoc-backend     |         address: 'mongo-pwndoc:27017',
pwndoc-backend     |         error: Error: connect ECONNREFUSED 172.20.0.2:27017
pwndoc-backend     |             at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
pwndoc-backend     |           name: 'MongoNetworkError',
pwndoc-backend     |           [Symbol(mongoErrorContextSymbol)]: {}
![2023-03-29_17-08-12 pdoc](https://user-images.githubusercontent.com/56800496/228678804-a80b7298-2f83-40b7-8dbc-7fbdbeb08e63.png)

**Comment by Zeecka** [comment]
It looks like you're not using the last version of pwndoc-ng (see the image name in screenshot).
![image](https://user-images.githubusercontent.com/24873615/228795100-09d368f9-f806-4f3d-934c-6d9d604faa99.png)
Maybe you need to re-build image without cache ( `docker compose build --no-cache`) ?
Can you verify that the user is registered with the followings commands (to check if you have data in your mongo container) :

```
docker exec -it mongo-pwndoc /bin/sh
mongo mongodb://127.0.0.1/pwndoc
db.users.find()
```

Please avoid leaking users passwords.
See https://github.com/pwndoc-ng/pwndoc-ng/blob/master/docs/debug.md#debug for more documentation.

**Comment by Zeecka** [comment]
It looks like you do not have the latest version of pwndoc-ng. 
First you can make a copy of your data (see https://github.com/pwndoc-ng/pwndoc-ng/issues/24):
- Copy the folder `./backend/mongo-data/` in a safe place. 
- Download the latest version of pwndoc-ng, build and run it.
- `docker ps -a` should give you image named `pwndoc-ng` without any reference tou "yeln4ts"
- Stop container, and replace `/var/lib/docker/volumes/pwndoc-ng_mongo-data/` content with content of previously saved `./backend/mongo-data/` content to recover your data.

**If you do not have any other containers running on your host**, then you can try remove the differents docker cache with the followings commands:
- `docker kill $(docker ps -q)`  
- `docker system prune --all`
- `docker volume rm $(docker volume ls -q)`  // /!\ may remove data
- `docker container prune`

**Please make a backup of your data before running thoses commands**.

**Comment by Zeecka** [comment]
Can you retry in an hour (see red error) ?

**Comment by bricekh2** [comment]
Yeah I just tried again which has been more then an hour. Still no luck. I also tried on a different VM and I got the same error.

**Comment by Zeecka** [comment]
It may be related to alpinelinux.org servers. Can you reach the following urls ?
- https://dl-cdn.alpinelinux.org/alpine/v3.16/main/
- https://dl-cdn.alpinelinux.org/alpine/v3.16/community/ 
- https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
- https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz

**Comment by bricekh2** [comment]
Yes I can reach all of those. Just tried it again and appears to be working. I have also moved my previous data base over and have successfully logged in! Looks like I am on the current version now as well. Thank you for your help!

**Comment by Zeecka** [comment]
Your welcome 😃
