### ISSUE TITLE
Breaking the template

### ISSUE THREAD

**Issue by relaxedricky** [pwndoc-ng/pwndoc-ng#152]
Bit of an odd one, I have found having the following within the PROOFS section of a vulnerability with both instances of https://example.com/ set to be a hyperlink, causes the generated Word document to fail to open.

```
-H $'Sec-Fetch-Dest: empty' -H $'Referer: https://example.com/'
$'https://example.com/'
```

Looking at the logs for the backend I see the following:

`pwndoc-ng-backend  | <w:p><w:r><w:t xml:space="preserve">-H $&apos;Sec-Fetch-Dest: empty&apos; -H $&apos;Referer: </w:t></w:r><w:r><w:rPr><w:rStyle w:val="Hyperlink"/></w:rPr><w:t xml:space="preserve"><w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText xml:space="preserve"> HYPERLINK https://example.com </w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r><w:r><w:rPr><w:rStyle w:val="Hyperlink"/></w:rPr><w:t> https://example.com|-|https://example.com}_|link|_}</w:t></w:r><w:r><w:t xml:space="preserve">&apos;</w:t></w:r></w:p><w:p><w:r><w:t xml:space="preserve">$&apos;</w:t></w:r><w:r><w:rPr><w:rStyle w:val="Hyperlink"/></w:rPr><w:t xml:space="preserve">{_|link|_{https://example.com </w:t> </w:r><w:r><w:fldChar w:fldCharType="end"/></w:r></w:t></w:r><w:r><w:t xml:space="preserve">&apos;</w:t></w:r></w:p>`

Tested with multiple templates.

**Comment by Serizao** [comment]
This pr may be solve your problem

**Comment by luminescence69** [comment]
I also have this exact issue

**Comment by Serizao** [comment]
Have you try with mentionned PR ?

**Comment by Syzik** [comment]
Can we close this issue ?
