### ISSUE TITLE
Custom selection for severity "None"/"Informational"

### ISSUE THREAD

**Issue by diggidong** [pwndoc-ng/pwndoc-ng#189]
Do we (on pwndoc-ng) have a solution for that https://github.com/pwndoc/pwndoc/issues/279 ?

By now it does not seem to work for cvss severity "None" or "Informational":
```
{#findings | where: ‘cvss.baseSeverity == “None”’ }
# do stuff
{/findings | where: ‘cvss.baseSeverity == „None”’ }
```

Should be from that check: https://github.com/pwndoc-ng/pwndoc-ng/blob/b40f26d17cd40052a23d89206fc1d41733c20dd9/backend/src/lib/report-generator.js#L434

**Comment by diggidong** [comment]
The interesting part is, that this one is working fine - function to print the headline:
```
{#findings | count: 'None'} 
4.5	Vulnerabilities with Risk Level Informational
{/findings | count: 'None'}
```

**Comment by Zeecka** [comment]
Simply:

```
{#findings | where: 'cvss.baseSeverity == ""'}
# do stuff
{/}
```

**Comment by diggidong** [comment]
we were able to solve it this way:
```
{#findings | where: ‘cvss.baseMetricScore == "0.0"’ | sortArrayByField: 'cvss.baseMetricScore':-1}
# do stuff
{/}
```

**Comment by Arszilla** [comment]
Is there a way to rename `None` to `Informational`? Because `None` has not the same message as `Informational`, when relaying the report etc. to a client.

**Comment by Arszilla** [comment]
> > Is there a way to rename `None` to `Informational`? Because `None` has not the same message as `Informational`, when relaying the report etc. to a client.
> 
> Hi Arszilla, what do you mean by rename it? Where? You can adjust your report template as you like. Only in the PwnDoc-ng web app the naming is fix until you change some source code.
> 
> By the way, "None" is the "industry standard" regarding to [CVSSv3.0](https://www.first.org/cvss/v3.0/specification-document#Qualitative-Severity-Rating-Scale) to which this naming refers.

Hey diggi,

I am well aware `None` is the industry standard in respect to CVSS (3.x). However, from my experience, when relaying "None" findings to a client (or depending on your report template), using `Informational` instead of `None` is more beneficial.

I was curious if there's a way to replace `None` with `Informational` without modifying the source code.

**Comment by Zeecka** [comment]
Instead of `{cvss.baseEverity}`, you can use:
```
{#cvss.baseSeverity == "None"}Informational{/}
{#cvss.baseSeverity != "None"}{cvss.baseEverity}{/}
```
