### ISSUE TITLE
Table Styles 

### ISSUE THREAD

**Issue by relaxedricky** [pwndoc-ng/pwndoc-ng#19]
I am not sure if I have missed it, but the ability to have the table use a set table style or have more than one option for this would be amazing.

**Comment by Zeecka** [comment]
Definitively agree, at least for primary row / column with a default style.

**Comment by RobertDoc** [comment]
The tables are a bit nicer with #36 and support table headers now. 

I can't see anywhere in the docxjs documentation where I can apply table style/layout that is in the document. I can add border styles and shading but it would then be hardcoded for everyone.

**Comment by Zeecka** [comment]
I'm closing this, this feature can be resolved using hardcoded custom table, pwndoc-ng custom fields and conditions. Moreover it is already possible to iterate inside a hardcoded cutom table.
