### ISSUE TITLE
linkto breaks template if '&' is in the url

### ISSUE THREAD

**Issue by cristianb84** [pwndoc-ng/pwndoc-ng#198]
Hello,
I am using linkto to create hyperlinks for the references.
working example : https://support.microsoft.com/help/5023049
not working example : https://support.microsoft.com/help/5023049&123
Can someone check this ?

**Comment by Zeecka** [comment]
Maybe you can url-encode `&`  --> `%26` as partial fix until we manage to fix the code.

**Comment by cristianb84** [comment]
Found the solution.
adding these in in the beginning of the linkTo function fixes the issue : 
    url = url.replace(/&/g, "&amp;");
    input = input.replace(/&/g, "&amp;");

**Comment by Serizao** [comment]
I will check that but I think it's better to url encode all char because if there are an other char which need to be be encode to not break the word document

**Comment by cristianb84** [comment]
Thank you. Applied url encoding. It's working.

**Comment by Zeecka** [comment]
Can you make a PR or submit your fix so we can patch the repo / close the issue ? Thanks @cristianb84

**Comment by cristianb84** [comment]
Hi,
Sorry for the late response. Here is my working linkto function :
expressions.filters.linkTo = function(input, url) {
    url = encodeURIComponent(url);
    input = encodeURIComponent(input);

    return '<w:r><w:fldChar w:fldCharType="begin"/></w:r>'
        + '<w:r><w:instrText xml:space="preserve"> HYPERLINK "' + url + '" </w:instrText></w:r>'
        + '<w:r><w:fldChar w:fldCharType="separate"/></w:r>'
        + '<w:r><w:rPr><w:rStyle w:val="Hyperlink"/></w:rPr>'
        + '<w:t>' + input + '</w:t>'
        + '</w:r><w:r><w:fldChar w:fldCharType="end"/></w:r>';
}

**Comment by Zeecka** [comment]
I reopen the issue until we implement your patch :) thanks

**Comment by cristianb84** [comment]
> Hi, Sorry for the late response. Here is my working linkto function : expressions.filters.linkTo = function(input, url) { url = encodeURIComponent(url); input = encodeURIComponent(input);
> 
> ```
> return '<w:r><w:fldChar w:fldCharType="begin"/></w:r>'
>     + '<w:r><w:instrText xml:space="preserve"> HYPERLINK "' + url + '" </w:instrText></w:r>'
>     + '<w:r><w:fldChar w:fldCharType="separate"/></w:r>'
>     + '<w:r><w:rPr><w:rStyle w:val="Hyperlink"/></w:rPr>'
>     + '<w:t>' + input + '</w:t>'
>     + '</w:r><w:r><w:fldChar w:fldCharType="end"/></w:r>';
> ```
> 
> }

This solution does not work. It no longer breaks the Word document, but it also does not deliver the use case of linkto ... The simplest approach for me would be to use "replace" and map special characters ... Will keep trying with "encodeURIComponent". But using the function as I posted above, the link is not displayed properly in the Word document, and also it includes in the hyperlink the file system path where the document is stored.
