### ISSUE TITLE
Add support for Tables 

### ISSUE THREAD

**Issue by RobertDoc** [pwndoc-ng/pwndoc-ng#2]
https://github.com/pwndoc/pwndoc/issues/355

**Comment by Zeecka** [comment]
This feature is part of the TipTap upgrade project:
TipTap (WYSIWYG) v2 implement lots of new feature including tables.
@nitek29 made a [fork](https://github.com/nitek29/pwndoc) with this feature (and TipTap v2), but we need to verify there is no regression.

**Comment by RobertDoc** [comment]
I've been using that fork daily for a week now and not seen any regressions that I've noticed. @nitek29 have you noticed any regressions?

**Comment by Zeecka** [comment]
Feel free to make a PR on this repo :).

**Comment by nitek29** [comment]
I've just made a PR on the offical repo.
feel free to check 
I will make a PR on this repo when I will have some time 
HF
