### ISSUE TITLE
Error: Password policy not met

### ISSUE THREAD

**Issue by diggidong** [pwndoc-ng/pwndoc-ng#213]
While adding a new collaborator, I get the error, that I did not met the password policy requirements:
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/9928172/3f20891d-9ce9-490e-b33e-10c6f4340f10)

I used the password "TestTest1234!1" which actually does met the requirements.
I observed, that the "password error" occurs on all kind of errors adding a collaborator.
So in my case I only had to change the email address to all lowercase and I was able to add the user without any changes to the previous password:
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/9928172/bc5deb39-7d81-4107-828d-ecc8805dcf45)

**Comment by B1udg3r** [comment]
A bypass to this is by exporting the current collaborators, then just copy and pasting the json format. After reimporting the collaborators you can then change the users password with no issue.

**Comment by shyam0904a** [comment]
@RobertDoc  I faced this issue, but got it fixed by clearing the auto-saved credentials and then was able to create collaborators without any warnings.
Hope this works!!
