### ISSUE TITLE
Using Custom Sections and Fields in Report Template

### ISSUE THREAD

**Issue by Arszilla** [pwndoc-ng/pwndoc-ng#232]
Hi there,

I'm trying to use a custom section (with the field name `executivesummary`) in my report template. This section has several fields added to it (mostly consisting of `input` or `editor` options). However, based on the docs and experimentation, I can't seem to figure out a way to reflect the input in these fields in the generated report.

I've tried primarily tried:

- `{#executivesummary}{field_name}{/executivesummary}`
- `{-w:p executivesummary}{field_name}{/executivesummary}`

along other "Hail Mary" ways, but whenever the report was generated, the areas/paragraphs that were supposed to have the custom section and its fields reflected would literally get wiped/vanished from the report, resulting in removed text.

How should one be deploying their custom sections with various custom fields in their report? Can you give examples to it and perhaps add it to the documentation in a more clear manner?

Thanks in advance!

**Comment by TheGrayFox92** [comment]
This may help you. Check the comments. https://github.com/pwndoc/pwndoc/issues/424

**Comment by Arszilla** [comment]
Managed to solve the issue. Had to use the Custom Field name at the start for some. i.e.:

```
{#executive_summary}{custom_label}{/executive_summary}

{#executive_summary.custom_label_with_editor}
{@text | convertHTML}
{/executive_summary.custom_label_with_editor}
```

Hope it helps someone else.
