### ISSUE TITLE
Changing severity color in word document

### ISSUE THREAD

**Issue by burtonc** [pwndoc-ng/pwndoc-ng#233]
I've tried to change the tones of the severity colors for the report when its export but the tones don't seem to change, has anyone done this before?

I've changed the following. Just to note, I've tried changing the color hex values around but there is no change in export.

`src/lib/report-generator.js:    var noneColor = settings.report.public.cvssColors.noneColor.replace('#4A86E8', '#3DADD0'); //default of blue ("#4A86E8")

src/lib/report-generator.js:    var lowColor = settings.report.public.cvssColors.lowColor.replace('#008000', '#35BA53'); //default of green ("#008000")

src/lib/report-generator.js:    var mediumColor = settings.report.public.cvssColors.mediumColor.replace('#f9a009', '#FFC702'); //default of yellow ("#f9a009")

src/lib/report-generator.js:    var highColor = settings.report.public.cvssColors.highColor.replace('#FF5D02', '#fe0000'); //default of red ("#fe0000")

src/lib/report-generator.js:    var criticalColor = settings.report.public.cvssColors.criticalColor.replace('#212121', '#FF5D02'); //default of black ("#212121")`

**Comment by PereProteus** [comment]
Have you tried just changing it under /settings (as an admin user)

![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/129476670/583835d1-239e-4633-813b-12b03febdc52)

**Comment by burtonc** [comment]
.
