### ISSUE TITLE
migrating data

### ISSUE THREAD

**Issue by AnotherWayIn** [pwndoc-ng/pwndoc-ng#24]
Hi,

I have a LOT of reports and data to migrate to this version. The doc says move over the backend/mongo-data folder, which i've done but this version doesn't appear to have that folder. I can only seem to migrate vulnerabilities, but would like to move all the users/customers/custom fields etc.
what's the best way to approach this pls?

thanks

**Comment by RobertDoc** [comment]
The old pwndoc will have a mongo-data folder which will need to be inserted into the location of your Docker volume with the same name. The mongo-data folder now lives in `/var/lib/docker/volumes/pwndoc-ng_mongo-data/` on my box.

Let me know how you get on but that should work if you replace everything in that _data folder with everything in your old `backend/mongo-data` folder.

**Comment by AnotherWayIn** [comment]
worked great thanks :)

**Comment by AnotherWayIn** [comment]
might want to add this tip to the readme for others migrating over

**Comment by TheZ3ro** [comment]
I suggest using `mongodump` and `mongorestore` from MongoDB:

`mongodump --uri="mongodb://127.0.0.1/pwndoc" --archive=pwndoc.archive`
`mongorestore --uri="mongodb://127.0.0.1/pwndoc" --archive=pwndoc.archive`

https://www.mongodb.com/docs/database-tools/mongodump/#examples

**Comment by RenderZ0n3** [comment]
@TheZ3ro , Could you please let me know if it is possible to migrate from pwndoc 0.4.0.??

https://github.com/pwndoc/pwndoc/releases/tag/v0.4.0

It is very critical. could you please guide how can I do that please?
