### ISSUE TITLE
Code Blocks

### ISSUE THREAD

**Issue by PereProteus** [pwndoc-ng/pwndoc-ng#257]
Has anyone had success getting code blocks to work. I've done the following:
1. Read this:
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/129476670/0133aecc-0d59-4af4-9863-370f107ee59e)
2. Set it as code in pwndoc:
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/129476670/7c5748c0-f29f-477c-91a5-9ee7a160aa1f)
3. created the 'CodeChar' style in the template:
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/129476670/b6a2adca-25e4-457b-8857-11f84c0ec15a)
4. Inside the template i have the set following for the observation:
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/129476670/c23ceae4-7334-4b74-b762-b6b0e496a7e2)
5. Yet it still prints as plain:
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/129476670/a58244a0-646f-4187-94fb-a75dc30ad693)

Not sure if anyone else has run in to this. cheers.

**Comment by diggidong** [comment]
Hi,

I am using the default configuration regarding code blocks and if I zoom in on the document, the font actually changes:
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/9928172/af961f86-66c7-4125-bf2b-84853dfe688f)

I also see a minor difference in the font styles in your screenshots.
Have you double clicked on them and checked the font?
It's definitely not 'code like' but it changes. So you simply have to define that 'monospace-grey-background' type you would like it to look alike.

**Comment by DannyDW** [comment]
Hi,

I made the same mistake trying to add a custom code style. 
If I'm remembering correctly, you should call the style `Code`, not `CodeChar`. `Char` is appended automatically.

You could check `styles.xml` inside the docx to see what styles are there.

**Comment by peregrinus** [comment]
ah why didnt I try that name. That works perfectly @DannyDW thank you.
