### ISSUE TITLE
ADD SECTIONS NOT SHOWING 

### ISSUE THREAD

**Issue by effortlessdevsec** [pwndoc-ng/pwndoc-ng#259]
<img width="1391" alt="image" src="https://github.com/pwndoc-ng/pwndoc-ng/assets/30777722/e626a5b7-f650-4a56-b4b8-42fce8a581a8">

**Comment by effortlessdevsec** [comment]
ALSO ON CREATING REPORT EXECUTIVE SUMMARY SHOWING BLANK

**Comment by RobertDoc** [comment]
You need to add custom sections in the last tab on that page.

![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/636856/8283d5af-07ea-40f3-9971-6fbfaccedbc8)
https://pwndoc-ng.github.io/pwndoc-ng/#/data?id=custom-sections
