### ISSUE TITLE
[Question] Install on Synology NAS?

### ISSUE THREAD

**Issue by rdtm443** [pwndoc-ng/pwndoc-ng#26]
Hello folks

During my search for a pentest reporting tool, I stumbled over PwnDoc-NG. Would love to install it on my Synology NAS, but due to lack of deeper knowledge concerning docker, I am not able to.

Did anyone achieve to install it on a Syno NAS? If yes, how?

Got other dockers running on it, installed either via docker command or docker-compose through portainer (stack). But with this, it seems a bit different.

Thanks a lot!

**Comment by Zeecka** [comment]
Have you try the following commands ? :
```
git clone git@github.com:pwndoc-ng/pwndoc-ng.git
cd pwndoc-ng
docker compose up -d
```
make sure ports are availables (8443, 4242).

**Comment by rdtm443** [comment]
> Have you try the following commands ? :
> 
> ```
> git clone git@github.com:pwndoc-ng/pwndoc-ng.git
> cd pwndoc-ng
> docker compose up -d
> ```
> 
> make sure ports are availables (8443, 4242).

Not yet, as I am trying to avoid having to ssh into my NAS and "manually" mess around with the base system. I prefer the path via Portainer, if possible :)

**Comment by Zeecka** [comment]
Docker files relay on local files when building. According to the current docker-compose.yml file, you need to setup 3 container (back, front & mongo) with a shared volume. I  think you may be able to set up such environment by looking at the current https://github.com/pwndoc-ng/pwndoc-ng/blob/master/docker-compose.yml .

**Comment by rdtm443** [comment]
Hey there. Sorry for not replying in due time, was super busy (and still am). Just wanted to let you know that the docker compose is working perfectly fine on the synology nas.. now i am able to write pentesting reports on the nas. thank you so much for keeping pwndoc alive! need to read my way through the docs in order to be able to efficiently write stuff.. create vulnerability db, template etc.
