### ISSUE TITLE
blank vulnerabilities

### ISSUE THREAD

**Issue by MorielHarush** [pwndoc-ng/pwndoc-ng#261]
While working in the system, when findings are changed, many times the system simply displays a white page and does not display the text written in the finding.
Solutions I carry out to overcome this are to restart the system or wait a while.
Can it be fixed permanently?

![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/93482738/02208505-098c-4910-8597-42514c6c9790)

**Comment by cris1198** [comment]
Hola MorielHarush,

I'm having issues with the audit section. I added new fields, for example, 'background', which contained images and text. However, when I logged in later, everything was blank. To retrieve and display that data from 'background', do I need to restart the containers? Should I use 'docker-compose down' and then 'docker-compose up -d --build' again?

**Comment by Syzik** [comment]
Update your repos it should be fixed by #368.
