### ISSUE TITLE
Collaborative Text Areas Sometimes Overwritten With Nothing

### ISSUE THREAD

**Issue by c0nf1den71al** [pwndoc-ng/pwndoc-ng#280]
# Collaborative Text Areas Sometimes Overwritten With Nothing
## Description
Hey,

I have been using pwndoc-ng recently and noticed that sometimes the content of textareas would vanish. At first I thought I was going insane and just forgetting to save the finding content. However, upon using the application more, I noticed that even data which had been saved for a while was disappearing. 

Upon further investigation this appears to be an issue relating to the findings taking a moment to load over WebSockets. I noticed a similar issue has been raised [here](https://github.com/pwndoc-ng/pwndoc-ng/issues/261).

After playing around with the application, I discovered that the issue is due to changing tabs (for example from "definition" to "proofs") before the textarea content has loaded in fully (due to that initial delay mentioned in the other issue). 

_PS. I will try and work on a fix to this issue myself if I get a moment, however, I am raising anyway._

## Steps to reproduce
1. Create a new finding and add content to the description and observation sections. 
2. Save the finding.
3. Navigate to the "proofs" tab
4. Switch back to the "definition" tab, and quickly (before the textarea content loads in) switch back to the "proofs" tab. 
5. Navigate to the "definition" tab one last time and observe that the contents of the textareas have been deleted.

Thanks.

**Comment by sudonoodle** [comment]
I can reproduce this also.

Can someone label? This is quite a damaging one.

**Comment by Serizao** [comment]
This PR should correct the problem. Let me know if you have any more problems or if everything works fine ^^

**Comment by kosztyua** [comment]
This does not seem to be fixed. Just updated to latest commit and can experience the issue.
