### ISSUE TITLE
Sort vulnerabilities by created time

### ISSUE THREAD

**Issue by lovelyjuice** [pwndoc-ng/pwndoc-ng#285]
There are lots of vulnerabilities and I want to view those created recently.
Can you add a column on vulnerabilities page like this?
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/20644461/4a9b3714-eb6e-4ba3-ae11-93192b765ded)

**Comment by Xample33** [comment]
For me is a nice feature, i've made a PR: #287 
Hope this helps!

**Comment by RobertDoc** [comment]
#287 merged - thank you for the PR!
