### ISSUE TITLE
[Improvement] API specification

### ISSUE THREAD

**Issue by NewlineDotBlog** [pwndoc-ng/pwndoc-ng#29]
Currently PwnDoc-ng offers a very useful api at `/api`, however no specification or documentation for this is available. As mentioned in the Pwndoc repository issue #183, could it be possible to implement this for PwnDoc-NG?

There are solutions available that should be able to automatically generate and offer a swagger interface for testing it, though I'm not sure about how viable these solutions/libraries are.

**Comment by RobertDoc** [comment]
I've submitted PR #30 to generate basic swagger docs and expose the UI on /api-docs.
