### ISSUE TITLE
Table "code block" not working in update

### ISSUE THREAD

**Issue by Elevennails** [pwndoc-ng/pwndoc-ng#304]
The new table functionality is brilliant, thanks for your efforts!

Most stuff works for me. However, "code" works ok, but "code block" doesn't print into the Word document as expected. For some reason, the content appears above the table. It doesn't matter if a blank line is inserted before the start of the code block either. You still get the same result.

![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/24990272/e6fbe13c-94bc-4752-80bd-dafc59e5f6d6)

Looks like colouring is fine.

it would be good if the code block appeared inside the table cell like this as intended in the app
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/24990272/0604a206-a792-412d-95d1-c83c3db1d3e0)

In the app it looks like this
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/24990272/90a3685d-3e02-4146-a0b4-1bee1051ebdb)

**Comment by RobertDoc** [comment]
I've asked @dfktvS2 to have a look if they have time, good issue, thanks!

**Comment by dfktvS2** [comment]
@Elevennails was this working before? Regardless, I will attempt get this fixed.

**Comment by dfktvS2** [comment]
@Elevennails can I get a copy of your template? I did some testing locally using a modified version of (what I think) is the default template. The results seem to be ok.

Source
<img width="532" alt="image" src="https://github.com/pwndoc-ng/pwndoc-ng/assets/64235915/65a140c0-3b9d-432f-8910-ac44615ce5a9">

Results
<img width="509" alt="image" src="https://github.com/pwndoc-ng/pwndoc-ng/assets/64235915/dcd95793-4ceb-4a52-a009-d393a467276b">

I am testing with Libre Office. Perhaps Word is the problem? Testing now.... and that looks fine as well.

Results Word
<img width="411" alt="image" src="https://github.com/pwndoc-ng/pwndoc-ng/assets/64235915/f45f390a-62aa-4b0f-bfc6-01e23f21d86e">

**Comment by Elevennails** [comment]
Hi Brad, 

Thanks for looking at this, these new tables could be revolutionary for me! This aids me in generating reports more closely matching our old pre-pwndoc document format, which was preferred.

The "code" is fine; try a "code block" (the one next to the code) as a multi-line. I see you did try a single line above.

Here's a redacted test template with the same issue.

[test_template.docx](https://github.com/pwndoc-ng/pwndoc-ng/files/14226972/test_template.docx)


This is the actual output result from the above template.

[actual_output_result.docx](https://github.com/pwndoc-ng/pwndoc-ng/files/14226973/actual_output_result.docx)

As you can see, the multi-line code block leaks from the table. There are 2 different presentations in this example. 
1. Inside a word table, we would normally have the description and resolution/remediation. 
2. Outside a word table just to see if it makes any difference (it doesn't).



This was what we were hoping to see as the expected result

[actual_output_result.docx](https://github.com/pwndoc-ng/pwndoc-ng/files/14227006/actual_output_result.docx)


This is a screenshot of the description from pwndoc
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/24990272/f0d420d0-72b4-4fcc-9827-a0d16358f29f)

This is  a screenshot of the resolution/remediation from pwndoc
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/24990272/c42bdbf6-cac2-49b5-981c-bd073208fc17)


Hope this helps

Thanks

Si

**Comment by dfktvS2** [comment]
@Elevennails sorry for the delayed response. Just now getting back to this. My examples did use the code block, you can tell by the black background on the `I am a code block` cell. That being said I did not have multiple lines in it. Though that shouldn't matter too much. After looking at your template. I suspect the issue lies in the use of tables within tables and docxtemplater not knowing what parent to put the content in. I will take a deeper look when i get some more time.

**Comment by dfktvS2** [comment]
turns out my assumptions were wrong. multi-line code blocks do not behave as expected.

<img width="1252" alt="image" src="https://github.com/pwndoc-ng/pwndoc-ng/assets/64235915/24dbfe0b-1fa2-4d1e-ae66-748e9fb2a97c">

I'll continue to work on this as I have time.
