### ISSUE TITLE
Make history of original pwndoc available in this repo (don't reimport but actual fork)

### ISSUE THREAD

**Issue by xerxoria** [pwndoc-ng/pwndoc-ng#32]
It would be nice if `pwndoc-ng` would be an actual fork of pwndoc and not a new repo with reimport - that would make it easy to verify the project origin and preserve useful history. 

Note that it is possible to create forks under [different names](https://github.blog/changelog/2022-04-12-you-can-now-name-your-fork-when-creating-it/).

**Comment by TheZ3ro** [comment]
Sadly, Github do not allow forks to have "Issues" and in general, forks are highly restricted.
An alternative that would be appreciated is to have the full git history inside this repo from the old pwndoc to the actual master

**Comment by Zeecka** [comment]
Response on old pwndoc project: https://github.com/pwndoc/pwndoc/issues/441#issuecomment-1422958006.
I'm closing the issue for now.
