### ISSUE TITLE
Sizing of table once it is generated

### ISSUE THREAD

**Issue by rudem323** [pwndoc-ng/pwndoc-ng#33]
Being able to add a table is an awesome feature but is there a way to set the size of the table in the doc?  The table comes out small and I have to resize it for each finding. 
![image](https://user-images.githubusercontent.com/47099672/215619113-470d370a-f8e6-4ed6-80a8-6cd623c6f3bd.png)

**Comment by RobertDoc** [comment]
PR #36 fixes this issue
