### ISSUE TITLE
Text Editor Table Formatting

### ISSUE THREAD

**Issue by rlfree** [pwndoc-ng/pwndoc-ng#334]
**Describe the solution you'd like**
Is there any plans to add formatting options for tables that are inserted into a Text Editor field? Specifically changing color fills for things like header rows.

**Describe alternatives you've considered**
I attempted to try to do this via convertHTML but did not see any options for tables, just images. I have been changing it manually after report generation.

**Comment by Elevennails** [comment]
If you are using the latest release of pwndoc-ng, this might work for you.

I've changed the H5 and H6 font pointers on the backend to a couple of Styles I've created in my word template. "Code" and "TableHeading" respectively. These Word styles have the expected word formatting for code blocks and table headings that i want.

Now, when I use the editor in pwndoc, if I highlight text and set it to H5 and H6. it gets formatted as consolas with normal tight spacing or table headers and when it prints in Word it uses the styles I've configured. As a bonus, this also works well in tables, and you can colour-highlight the text, too. Which you can't do if you use the pwndoc builtin codeblocks formatting.

You do lose the ability to use H5 and H6 for other stuff, but I do all my formatting in Word anyway

I've modified a couple of lines in: backend/src/lib/html2ooxml.js file as shown below (see inline comments)

```
        if (tag === "h1") {
          cParagraph = new docx.Paragraph({ heading: "Heading1" });
        } else if (tag === "h2") {
          cParagraph = new docx.Paragraph({ heading: "Heading2" });
        } else if (tag === "h3") {
          cParagraph = new docx.Paragraph({ heading: "Heading3" });
        } else if (tag === "h4") {
          cParagraph = new docx.Paragraph({ heading: "Heading4" });
        } else if (tag === "h5") {
          cParagraph = new docx.Paragraph({ heading: "Code" });      // This used to be Heading 5, Code is a word Style
        } else if (tag === "h6") {
          cParagraph = new docx.Paragraph({ heading: "TableHeading" });     // This used to be Heading 6, it's also a Style
        } else if (tag === "div" || tag === "p") {
```

Then I Added the following to the end of: frontend/src/css/quasar.variables.styl

```
// This sets the CSS style for h5 in pwndoc so the font looks as expected in your browser.
h5 {
  font-family: Consolas, monaco, monospace;
  font-size: 14px;
  font-weight: normal; /* Set the font weight to normal */
  margin-top: 0;
  margin-bottom: 0;
  line-height: 1.0;
  pointer-events: none;
}
// This sets the table header font type so it looks ok in pwndoc. Unfortunately, it doesn't center in the browser table. 
// but my Word Style does this automatically as part of the style when it prints the report.
h6 {
  font-size: 1em;
  font-weight: bold;
  font-align: center;
  line-height: 1;
  white-space: nowrap;
}
```

Then just restart pwndoc with the --build option to add the changes in to your running app.

docker compose up --build.

Now I can make code blocks with highlighting and add centred table headings in Word. You might feel this is a dirty hack but it's %100 usable. It doesn't seem to adversely affect any of the pwndoc app headings. For me it's a win win. You'd have to remember to mod the files again if you update in the future.

PS. I know nothing if you break pwndoc-ng it's on you :)

Good luck
Si

**Comment by rlfree** [comment]
Thanks for your input on this. I ended up just writing a VBA macro to do it post generation.
