### ISSUE TITLE
Regression with, bookmarkCreate, bookmarklink and linkTo

### ISSUE THREAD

**Issue by Zeecka** [pwndoc-ng/pwndoc-ng#39]
According to @drunkentortoise https://github.com/pwndoc-ng/pwndoc-ng/pull/10#issuecomment-1419462360

" Just a quick question, due to the upgrade of the codeblock function and TipTapv2, some filter features such as bookmarkCreate, bookmarklink and linkTo are no longer present in the report-generator.js. For now, I was able to recover the js file from the initial commit as a workaround."

**Comment by drunkentortoise** [comment]
I will check it and let you know. Thank :)

Also, It's a long shot, but I'm currently trying to implement a checklist on the frontend with buttons and so on for each audit what will later reflect on each generated report. 

So far, I've managed to add a dedicated section in Audit page (under findings) and display a few buttons, but I'm having a hard time removing and rebuilding my containers. Would it be possible to know if there is a way to get the DEV version up and running ? Being able to see the result of the changes I make can save me a ton of time.

**Comment by drunkentortoise** [comment]
> #40 should have fix the issue, @drunkentortoise let me know if it works on your side.

I pulled with the merge #40 and everything seems to be working so far ! :smile:

**Comment by Zeecka** [comment]
> I will check it and let you know. Thank :)
> 
> Also, It's a long shot, but I'm currently trying to implement a checklist (WSTG) on the frontend with buttons and so on for each audit what will later reflect on each generated report.
> 
> So far, I've managed to add a dedicated section in Audit page (under findings) and display a few buttons, but I'm having a hard time removing and rebuilding my containers. Would it be possible to know if there is a way to get the DEV version up and running ? Being able to see the result of the changes I make can save me a ton of time.

Can you open an new issue for the dev version ? I'm closing this one :)
