### ISSUE TITLE
URL encoding in references breaks hyperlink

### ISSUE THREAD

**Issue by Fopje** [pwndoc-ng/pwndoc-ng#399]
When creating a report, any url placed inside the references field of a finding is automatically getting URL encoded, destroying the hyperlink.

Adding URL
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/4934752/b566a1cb-9647-4d19-a597-17a4538eea49)

Exported (custom) template
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/4934752/c91587f0-76fa-448e-b601-e97b22bd2c39)

Exported (default) template
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/4934752/97597f93-4aeb-48ab-8096-a55791395c2d)

**Comment by diggidong** [comment]
That also affects other links like the CVSS v3.1 Vector from the [documentation](https://pwndoc-ng.github.io/pwndoc-ng/#/docxtemplate?id=linkto): `{@cvss.vectorString | linkTo: 'https://www.first.org/cvss/calculator/3.1#' + cvss.vectorString | p}`

Which gets formatted like this:
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/9928172/f5db6cfc-9811-4401-bfd2-77a234e465df)

What also is strange, that when hovering over the link, you see local paths:
![image](https://github.com/pwndoc-ng/pwndoc-ng/assets/9928172/196a1e8f-7a79-4629-a015-b197a9fbe31b)

**Comment by aguyinahoodie** [comment]
This is related to the decision to use encodeURIComponent in #198 and #373 - which stops the & character breaking the document but seems to have broken the actual linkto functionality. I've found that swapping to the encodeURI component fixes the issue (assuming we still want to URI encode some values), but you then still need to manually swap the & symbol out to avoid that breaking the document.

Changing the following within ```backend/src/lib/html2ooxml.js``` should fix it for now until there's a more permanent solution:

**Before**
```
var encodedUrl = encodeURIComponent(url); // fix breaking word with special characters in reference
var encodedInput = encodeURIComponent(input); // fix breaking word with special characters in reference
```
**After**
```
url = url.replace(/&/g, '%26'); // fix breaking word with special characters in reference
input = input.replace(/&/g, '%26'); // fix breaking word with special characters in reference
var encodedUrl = encodeURI(url); 
var encodedInput = encodeURI(input); 
```

**Comment by Papyxulo** [comment]
I've created a pull request https://github.com/pwndoc-ng/pwndoc-ng/pull/406 to solve this.
It also removes the odd shading that appeared in the generated links in office 365

**Comment by Syzik** [comment]
![image](https://github.com/user-attachments/assets/fc8acaae-998d-4b1c-9ad6-32f4a707e2df)

It seems good
I'll close the issue. If you find another bug, feel free to reopen it.
