### ISSUE TITLE
Websocket on loadbalancing

### ISSUE THREAD

**Issue by nitek29** [pwndoc-ng/pwndoc-ng#60]
Websocket doesn't work on load balanced instance.
error : {"code":1,"message":"Session ID unknown"}

**Comment by Zeecka** [comment]
cc @Serizao

**Comment by Serizao** [comment]
Hello @nitek29  can you provide us more information : schema of infrastructure endpoint etc to try to reproduce

**Comment by Serizao** [comment]
This question has been open for two months without answer. I close it
