### ISSUE TITLE
[BUG] Default text of custom sections disappears

### ISSUE THREAD

**Issue by randshell** [pwndoc-ng/pwndoc-ng#69]
After adding some text as default and saving it in the custom section, upon page reload this default text disappears. When creating a new Audit, however, the text is there so it appears to be a visual bug. After testing, it looks to have been introduced by the collab patches of #57 

![image](https://user-images.githubusercontent.com/43271778/221147469-f62216b1-4ef5-468b-925b-538de149daed.png)

**Comment by Zeecka** [comment]
This might be a related issue: https://github.com/pwndoc-ng/pwndoc-ng/issues/46. I think both can be soled in a single PR.

**Comment by Serizao** [comment]
This should solve this issue
