### ISSUE TITLE
Allow pasting of images AND text from clipboard

### ISSUE THREAD

**Issue by randshell** [pwndoc-ng/pwndoc-ng#75]
It'd be really nice to allow the pasting of images from the clipboard into the editor. I saw some code referencing this, but it's not actually supported by the editor.

https://github.com/pwndoc-ng/pwndoc-ng/blob/97721991c837ee362ef46d11ece1481b47a11188/frontend/src/components/editor-image.js#L132-L134

**Comment by Zeecka** [comment]
Well, AFAIK it use to work on original pwndoc. This is an important regression :/

**Comment by RobertDoc** [comment]
I haven't updated to the collaboration version yet and I can still paste images - is this a regression from the collaboration changes?

**Comment by RobertDoc** [comment]
I've updated to the latest master and it doesn't install correctly, Hocuspocus is runs on port 8440 which isn't exposed to the frontend and the socket doesn't seem to be connecting - has anyone tried a fresh install with the current main branch?

**Comment by Zeecka** [comment]
cc @Serizao

**Comment by BZHunt** [comment]
yep it's normal hocupocus is expose over reverse proxy (/collab) . Personnally i'm on the latest version. @RobertDoc have you any log or other ?

I confirm, pasting image seem not wrork with block of text. But picture only, pasting seem work

**Comment by Serizao** [comment]
It's normal for Hocupocus it will be join from reverse proxy (endpoint /collab port 443). I'm on the latest version. @RobertDoc have you any log or description that not working ?

For pasting image i confirme when we past image with text it not work but image only, that seem be work.

**Comment by RobertDoc** [comment]
@Serizao are you able to checkout the main branch and get it running without any additional steps? Since the collaboration merge my build is completely broken

**Comment by Serizao** [comment]
i confirm that it work to me @RobertDoc

**Comment by Zeecka** [comment]
I just tested (latest prod commit), image pasting works fine as long as you only have an image in your cliboard (ie. flameshot). This is not a regression (it doesn't work also on original pwndoc).

**Comment by RobertDoc** [comment]
Have you tried it on the dev version? It doesn't paste the image at all

**Comment by Serizao** [comment]
For me on the old pwndoc was possible to paste a block of text also composed of image it worked. 
Another thing that worked with images and that no longer works is that when copying and pasting from html the alt attribute came directly into the caption of the image which is no longer the case

**Comment by Zeecka** [comment]
@Serizao I tested on latest "old pwndoc", (copy past from libreoffice), it didn't worked. @RobertDoc I'm gonna have a try and let you know. Since people keep doing PR on Main branch, I no longer use it :/ ...

**Comment by Zeecka** [comment]
![image](https://user-images.githubusercontent.com/24873615/222789479-f4c32f44-45a7-40ff-ab13-4092cc6deb8e.png)
Works on dev branch for me

**Comment by Serizao** [comment]
it worked with base64 encoded images directly in the source :

![image](https://user-images.githubusercontent.com/11671895/222792484-bdd0eb46-9f8f-4eb2-add6-a37f80d117dc.png)

html source to reproduce :

```
This placeholder image generator offers a lot of options, including width and height, ratios, background and foreground color, and our favorite—common preset screen and ad sizes.


  <img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
```

**Comment by Serizao** [comment]
b64 image pasting was solve by [#Add pasting of html contain b64 img](https://github.com/pwndoc-ng/pwndoc-ng/commit/50cd56cd9d594a57f5b3407ee5610d5d9b4aaba1)
