### ISSUE TITLE
condition on existing vulnerability severity

### ISSUE THREAD

**Issue by diggidong** [pwndoc-ng/pwndoc-ng#81]
Hi everyone,

I am looking for a way to check if vulnerabilities of a certain severity exist and only execute/print a line once, if true.
So the idea is to have a title i.e. 'Vulnerabilities with risk level High' and list the vulns itself in a subheadings afterwards. So if I don't have vulns of a particular risk level, the title should not be printed.
I tried it with 
```
{#findings}
{#cvss.baseSeverity == 'High'}
4.2. Vulnerabilities with Risk Level {cvss.baseSeverity}
{/cvss.baseSeverity == 'High'}
{/findings}

```
but it printed the title multiple times (as often as vulns with a particular severity exists.

The 'uniqFindings' filter from the [Issue 413](https://github.com/pwndoc/pwndoc/issues/413) also didn't work as it only checks for unique names..

Is there any build in function which is doing the job?
Am I missing something?

**Comment by Zeecka** [comment]
You can use `{#findings | count: 'High'}`, see https://github.com/pwndoc-ng/pwndoc-ng/blob/master/backend/src/lib/report-generator.js#L451

**Comment by diggidong** [comment]
That worked pretty smooth!
Thanks a lot!
We have to update the documentation for such "hidden" functions by time.
Pretty helpful.
Thanks!
